dependencies:
  build:
    - go:1.12.1

build_targets:
  - name: docker_image
    commands:
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sh get-docker.sh
      - docker build . -f Dockerfile.ubuntu -t yb_ubuntu

ci:
  builds:
    - name: docker
      build_target: docker_image
      
    
