FROM ubuntu:18.04
RUN apt update
RUN apt install -y git
RUN apt install -y build-essential
RUN apt install -y libssl-dev libreadline-dev zlib1g-dev libbz2-dev libsqlite3-dev ca-certificates
RUN apt install -y wget curl
